import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, fireEvent, act, within } from '@testing-library/react';
import { useEffect } from 'react';
import StandardSetup from './StandardSetup';
import PlayerTracker from './PlayerTracker';
import JoinPage from './JoinPage';

interface SocketSubscription {
  gameCode: string;
  onMessage: (data: unknown) => void;
}

const activeSubscriptions: SocketSubscription[] = [];

// Mock useGameSocket to route messages between components sharing the same game code
vi.mock('./hooks/useGameSocket', () => {
  return {
    useGameSocket: vi.fn((gameCode: string, onMessage: (data: unknown) => void) => {
      useEffect(() => {
        if (!gameCode) return;
        const sub = { gameCode, onMessage };
        activeSubscriptions.push(sub);
        return () => {
          const idx = activeSubscriptions.indexOf(sub);
          if (idx !== -1) {
            activeSubscriptions.splice(idx, 1);
          }
        };
      }, [gameCode, onMessage]);

      const sendMessage = vi.fn(async (payload: unknown) => {
        // Simulate network latency
        await new Promise((resolve) => setTimeout(resolve, 10));
        // Run callbacks in act since they update component state
        act(() => {
          activeSubscriptions.forEach((sub) => {
            if (sub.gameCode.toLowerCase() === gameCode.toLowerCase()) {
              sub.onMessage(payload);
            }
          });
        });
      });

      return {
        isConnected: !!gameCode,
        sendMessage,
      };
    })
  };
});

describe('Storyteller Reset Integration', () => {
  beforeEach(() => {
    localStorage.clear();
    sessionStorage.clear();
    activeSubscriptions.length = 0;
    vi.clearAllMocks();
  });

  it('notifies and disconnects a joined PlayerTracker when storyteller resets the game', async () => {
    window.location.hash = '#/standard';
    const confirmSpy = vi.spyOn(window, 'confirm').mockReturnValue(true);
    let codeAtAlert: string | null = null;
    const alertSpy = vi.spyOn(window, 'alert').mockImplementation(() => {
      codeAtAlert = localStorage.getItem('standard-botc-game-code');
    });

    // 1. Render the Storyteller setup page to generate the game session
    const { container: storytellerContainer, unmount: unmountStoryteller } = render(
      <StandardSetup theme="dark" toggleTheme={vi.fn()} />
    );

    // Retrieve the game code generated by StandardSetup
    const gameCode = localStorage.getItem('standard-botc-game-code');
    expect(gameCode).toBeDefined();
    expect(gameCode?.length).toBe(4);

    // 2. Set the player's joined game code in sessionStorage to mock joining the session
    sessionStorage.setItem('joined-code', gameCode!);

    // 3. Render the PlayerTracker client
    const { container: trackerContainer, unmount: unmountTracker } = render(
      <PlayerTracker theme="dark" toggleTheme={vi.fn()} />
    );
    const tracker = within(trackerContainer);

    // Verify PlayerTracker is synced and showing the notice
    expect(
      tracker.getByText(/seating arrangement and player list are synced/i)
    ).toBeInTheDocument();

    // 4. Trigger reset game on the Storyteller page
    const resetButton = storytellerContainer.querySelector('#reset-game-button');
    expect(resetButton).not.toBeNull();

    await act(async () => {
      fireEvent.click(resetButton!);
      await new Promise((resolve) => setTimeout(resolve, 30));
    });

    // Verify confirm was called
    expect(confirmSpy).toHaveBeenCalled();

    // Verify storyteller hash is reset to home (main menu)
    expect(window.location.hash).toBe('');

    // Verify player client received 'storyteller_quit' message via mock socket, showed the alert,
    // and reverted the UI back to local tracker mode
    expect(alertSpy).toHaveBeenCalledWith(
      'The Storyteller has quit the session. Reverting to local tracker.'
    );
    // Verify that the code at the alert moment was still the old code (awaited correctly)
    expect(codeAtAlert).toBe(gameCode);

    // Verify the seating arrangement sync notice is gone and player list input is enabled
    expect(tracker.queryByText(/seating arrangement and player list are synced/i)).toBeNull();
    expect(tracker.getByPlaceholderText('Enter player name in seating order...')).toBeInTheDocument();

    unmountStoryteller();
    unmountTracker();
    confirmSpy.mockRestore();
    alertSpy.mockRestore();
  });

  it('notifies and disconnects a joined JoinPage client when storyteller resets the game', async () => {
    window.location.hash = '#/standard';
    const confirmSpy = vi.spyOn(window, 'confirm').mockReturnValue(true);
    let codeAtAlert: string | null = null;
    const alertSpy = vi.spyOn(window, 'alert').mockImplementation(() => {
      codeAtAlert = localStorage.getItem('standard-botc-game-code');
    });

    // 1. Render Storyteller to get game session
    const { container: storytellerContainer, unmount: unmountStoryteller } = render(
      <StandardSetup theme="dark" toggleTheme={vi.fn()} />
    );

    const gameCode = localStorage.getItem('standard-botc-game-code');
    expect(gameCode).toBeDefined();

    // 2. Simulate joined state for JoinPage
    sessionStorage.setItem('joined-code', gameCode!);
    sessionStorage.setItem('joined-name', 'Alice');

    // 3. Render JoinPage
    const { container: joinContainer, unmount: unmountJoinPage } = render(
      <JoinPage theme="dark" toggleTheme={vi.fn()} />
    );
    const joinPage = within(joinContainer);

    // JoinPage should be in the waiting room / waiting state
    expect(joinPage.getByText(new RegExp(`Joined Room ${gameCode}`, 'i'))).toBeInTheDocument();

    // 4. Trigger reset on Storyteller setup page
    const resetButton = storytellerContainer.querySelector('#reset-game-button');
    expect(resetButton).not.toBeNull();

    await act(async () => {
      fireEvent.click(resetButton!);
      await new Promise((resolve) => setTimeout(resolve, 30));
    });

    // Verify storyteller hash is reset to home (main menu)
    expect(window.location.hash).toBe('');

    // Verify JoinPage was notified, showed alert, and reverted back to the join screen
    expect(alertSpy).toHaveBeenCalledWith('The Storyteller has quit the session.');
    // Verify that the code at the alert moment was still the old code (awaited correctly)
    expect(codeAtAlert).toBe(gameCode);
    expect(joinPage.getByPlaceholderText('e.g. KVTQ')).toBeInTheDocument();

    unmountStoryteller();
    unmountJoinPage();
    confirmSpy.mockRestore();
    alertSpy.mockRestore();
  });
});
