import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, fireEvent, act, within, waitFor } from '@testing-library/react';
import { useEffect } from 'react';
import StandardSetup from './StandardSetup';
import WhaleBucket from './WhaleBucket';
import PlayerTracker from './PlayerTracker';
import JoinPage from './JoinPage';
import type { PlacedReminder } from './types';

interface SocketSubscription {
  gameCode: string;
  onMessage: (data: unknown) => void;
}

const activeSubscriptions: SocketSubscription[] = [];
const sentPayloads: Array<{ gameCode: string; payload: unknown }> = [];

// Mock useGameSocket to route messages between components sharing the same game code
vi.mock('./hooks/useGameSocket', () => {
  return {
    useGameSocket: vi.fn((gameCode: string, onMessage: (data: unknown) => void) => {
      useEffect(() => {
        if (!gameCode) return;
        const sub = { gameCode, onMessage };
        activeSubscriptions.push(sub);
        return () => {
          const idx = activeSubscriptions.indexOf(sub);
          if (idx !== -1) {
            activeSubscriptions.splice(idx, 1);
          }
        };
      }, [gameCode, onMessage]);

      const sendMessage = vi.fn(async (payload: unknown) => {
        sentPayloads.push({ gameCode, payload });
        // Simulate network latency
        await new Promise((resolve) => setTimeout(resolve, 10));
        // Run callbacks in act since they update component state
        act(() => {
          activeSubscriptions.forEach((sub) => {
            if (sub.gameCode.toLowerCase() === gameCode.toLowerCase() && sub.onMessage !== onMessage) {
              sub.onMessage(payload);
            }
          });
        });
      });

      return {
        isConnected: !!gameCode,
        sendMessage,
      };
    })
  };
});

describe('Storyteller Reset Integration', () => {
  beforeEach(() => {
    localStorage.clear();
    sessionStorage.clear();
    activeSubscriptions.length = 0;
    sentPayloads.length = 0;
    vi.clearAllMocks();
  });

  it('notifies and disconnects a joined PlayerTracker when storyteller resets the game', async () => {
    window.location.hash = '#/standard';

    // 1. Render the Storyteller setup page to generate the game session
    const { container: storytellerContainer, unmount: unmountStoryteller } = render(
      <StandardSetup theme="dark" toggleTheme={vi.fn()} />
    );

    // Retrieve the game code generated by StandardSetup
    const gameCode = localStorage.getItem('standard-botc-game-code');
    expect(gameCode).toBeDefined();
    expect(gameCode?.length).toBe(4);

    // 2. Set the player's joined game code in sessionStorage to mock joining the session
    sessionStorage.setItem('joined-code', gameCode!);

    // 3. Render the PlayerTracker client
    const { container: trackerContainer, unmount: unmountTracker } = render(
      <PlayerTracker theme="dark" toggleTheme={vi.fn()} />
    );
    const tracker = within(trackerContainer);

    // Verify PlayerTracker is synced and showing the notice
    expect(
      tracker.getByText(/seating arrangement and player list are synced/i)
    ).toBeInTheDocument();

    // 4. Trigger reset game on the Storyteller page — click reset then confirm the modal
    const resetButton = storytellerContainer.querySelector('#reset-game-button');
    expect(resetButton).not.toBeNull();

    fireEvent.click(resetButton!);

    // Confirm modal should appear — click to proceed with reset
    const confirmButton = storytellerContainer.querySelector('#dialog-confirm-button');
    expect(confirmButton).not.toBeNull();

    await act(async () => {
      fireEvent.click(confirmButton!);
      await new Promise((resolve) => setTimeout(resolve, 30));
    });

    // Verify storyteller returns to the mode's setup page (not home)
    expect(window.location.hash).toBe('#/standard');

    // Verify player client received 'storyteller_quit' message and reverted UI
    expect(tracker.getByText('The Storyteller has quit the session. Reverting to local tracker.')).toBeInTheDocument();
    expect(tracker.queryByText(/seating arrangement and player list are synced/i)).toBeNull();
    expect(tracker.getByPlaceholderText('Enter player name in seating order...')).toBeInTheDocument();

    unmountStoryteller();
    unmountTracker();
  });

  it('notifies and disconnects a joined JoinPage client when storyteller resets the game', async () => {
    window.location.hash = '#/standard';

    // 1. Render Storyteller to get game session
    const { container: storytellerContainer, unmount: unmountStoryteller } = render(
      <StandardSetup theme="dark" toggleTheme={vi.fn()} />
    );

    const gameCode = localStorage.getItem('standard-botc-game-code');
    expect(gameCode).toBeDefined();

    // 2. Simulate joined state for JoinPage
    sessionStorage.setItem('joined-code', gameCode!);
    sessionStorage.setItem('joined-name', 'Alice');

    // 3. Render JoinPage
    const { container: joinContainer, unmount: unmountJoinPage } = render(
      <JoinPage theme="dark" toggleTheme={vi.fn()} />
    );
    const joinPage = within(joinContainer);

    // JoinPage should be in the waiting room / waiting state
    expect(joinPage.getByText(new RegExp(`Joined Room ${gameCode}`, 'i'))).toBeInTheDocument();

    // 4. Trigger reset on Storyteller setup page — click reset then confirm the modal
    const resetButton = storytellerContainer.querySelector('#reset-game-button');
    expect(resetButton).not.toBeNull();

    fireEvent.click(resetButton!);

    // Confirm modal should appear — click to proceed with reset
    const confirmButton = storytellerContainer.querySelector('#dialog-confirm-button');
    expect(confirmButton).not.toBeNull();

    await act(async () => {
      fireEvent.click(confirmButton!);
      await new Promise((resolve) => setTimeout(resolve, 30));
    });

    // Verify storyteller returns to the mode's setup page (not home)
    expect(window.location.hash).toBe('#/standard');

    // Verify JoinPage was notified and reverted back to the join screen
    expect(joinPage.getByText('The Storyteller has quit the session.')).toBeInTheDocument();
    expect(joinPage.getByPlaceholderText('e.g. KVTQ')).toBeInTheDocument();

    unmountStoryteller();
    unmountJoinPage();
  });

  // Renders a storyteller mid-game with one revealed remote player (Alice),
  // returning handles plus Alice's current JoinPage screen state.
  async function renderGameWithRevealedPlayer() {
    localStorage.setItem('standard-botc-game-code', 'RKMP');
    localStorage.setItem('standard-botc-sync-code', 'RSNC');
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' }],
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    }));

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = localStorage.getItem('standard-botc-game-code')!;

    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Alice');
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    // Let the join round-trip complete: Alice announces herself, the
    // storyteller registers her + broadcasts the game, Alice reveals.
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 200));
    });

    return { storyteller, joinPage, gameCode };
  }

  it('opens the reset choice modal (not a plain confirm) when a player is connected', async () => {
    const { storyteller, joinPage } = await renderGameWithRevealedPlayer();

    // Alice should be revealed as her character
    expect(joinPage.queryAllByText('Washerwoman').length).toBeGreaterThan(0);

    fireEvent.click(storyteller.container.querySelector('#reset-game-button')!);

    expect(storyteller.container.querySelector('#reset-game-modal')).not.toBeNull();
    expect(within(storyteller.container).getByText('Keep Players')).toBeInTheDocument();
    expect(within(storyteller.container).getByText('Disconnect')).toBeInTheDocument();
    expect(within(storyteller.container).getByText('Cancel')).toBeInTheDocument();

    // Cancel closes it and sends nothing
    fireEvent.click(within(storyteller.container).getByText('Cancel'));
    expect(storyteller.container.querySelector('#reset-game-modal')).toBeNull();
    expect(sentPayloads.some(p => (p.payload as { type?: string }).type === 'game_reset')).toBe(false);
    expect(sentPayloads.some(p => (p.payload as { type?: string }).type === 'storyteller_quit')).toBe(false);

    storyteller.unmount();
    joinPage.unmount();
  });

  it('the setup-header Reset button opens the same reset choice modal', async () => {
    // Storyteller in setup phase with one connected player.
    localStorage.setItem('standard-botc-game-code', 'STUP');
    localStorage.setItem('standard-botc-sync-code', 'STUS');
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' }],
      phase: 'setup',
    }));
    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    sessionStorage.setItem('joined-code', 'STUP');
    sessionStorage.setItem('joined-name', 'Alice');
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 200));
    });

    // The header line reset button lives in the setup phase.
    const setupResetBtn = storyteller.container.querySelector('#setup-reset-button');
    expect(setupResetBtn).not.toBeNull();
    fireEvent.click(setupResetBtn!);

    expect(storyteller.container.querySelector('#reset-game-modal')).not.toBeNull();
    expect(within(storyteller.container).getByText('Keep Players')).toBeInTheDocument();

    storyteller.unmount();
    joinPage.unmount();
  });

  it('does NOT re-show the grimoire confirm after the Back button returns to setup', async () => {
    // The header Back button steps back to setup WITHOUT re-arming the one-time
    // "Send character assignments?" warning: you've already acknowledged
    // sending assignments, so re-opening should not nag again. (Only a Reset —
    // Keep Players / Disconnect — re-arms it.)
    localStorage.setItem('standard-botc-game-code', 'RCFM');
    localStorage.setItem('standard-botc-sync-code', 'RCFS');
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: [
        { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' },
        { id: 'p2', name: 'Bob', isDead: false, roleId: 'chef' },
        { id: 'p3', name: 'Cara', isDead: false, roleId: 'empath' },
        { id: 'p4', name: 'Dave', isDead: false, roleId: 'poisoner' },
        { id: 'p5', name: 'Eve', isDead: false, roleId: 'imp' },
      ],
      phase: 'setup',
    }));
    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = 'RCFM';

    await act(async () => { await new Promise(r => setTimeout(r, 50)); });

    // A remote player announces herself so remotePlayerCount > 0 (the confirm
    // only shows when connected players will receive assignments).
    await act(async () => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage({ type: 'player_join', id: 'p1', name: 'Alice' }));
      await new Promise(r => setTimeout(r, 50));
    });

    const openBtn = () => storyteller.container.querySelector('#open-grimoire-button') as HTMLButtonElement;
    expect(openBtn()).not.toBeNull();
    expect(openBtn().disabled).toBe(false);

    // First open → confirm modal appears → confirm it.
    fireEvent.click(openBtn());
    expect(within(storyteller.container).getByText('Send character assignments?')).toBeInTheDocument();
    await act(async () => {
      fireEvent.click(storyteller.container.querySelector('#confirm-open-grimoire-button')!);
      await new Promise(r => setTimeout(r, 50));
    });
    expect(storyteller.container.querySelector('#open-grimoire-button')).toBeNull();

    // Back to setup via the header back button (roles are kept).
    await act(async () => {
      fireEvent.click(storyteller.container.querySelector('#page-back-button')!);
      await new Promise(r => setTimeout(r, 50));
    });
    expect(openBtn()).not.toBeNull();

    // Re-open → NO confirm; the grimoire opens straight through.
    await act(async () => {
      fireEvent.click(openBtn());
      await new Promise(r => setTimeout(r, 50));
    });
    expect(within(storyteller.container).queryByText('Send character assignments?')).toBeNull();
    expect(storyteller.container.querySelector('#open-grimoire-button')).toBeNull();

    storyteller.unmount();
  });

  it('a synced storyteller pressing back at setup gets the reset modal, not a silent exit', async () => {
    localStorage.setItem('standard-botc-game-code', 'BGRD');
    localStorage.setItem('standard-botc-sync-code', 'BGRS');
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: '' }],
      phase: 'setup',
    }));
    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    sessionStorage.setItem('joined-code', 'BGRD');
    sessionStorage.setItem('joined-name', 'Alice');
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 200));
    });

    // With a connected player, the back control is an in-app button (no href).
    const backBtn = storyteller.container.querySelector('#page-back-button')!;
    expect(backBtn.tagName).toBe('BUTTON');
    fireEvent.click(backBtn);

    expect(storyteller.container.querySelector('#reset-game-modal')).not.toBeNull();

    // Cancel keeps the storyteller in the game (still on #/standard).
    fireEvent.click(within(storyteller.container).getByText('Cancel'));
    expect(storyteller.container.querySelector('#reset-game-modal')).toBeNull();
    expect(window.location.hash).toBe('#/standard');

    storyteller.unmount();
    joinPage.unmount();
  });

  it('a synced game-tracker player pressing back at setup gets the disconnect confirm, not a silent exit', async () => {
    sessionStorage.setItem('joined-code', 'TBCK');
    sessionStorage.setItem('joined-name', 'Zoe');
    localStorage.setItem('player-tracker-botc-game', JSON.stringify({ players: [], phase: 'setup', code: 'TBCK' }));
    window.location.hash = '#/tracker';
    const tracker = render(<PlayerTracker theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 80));
    });

    const backBtn = tracker.container.querySelector('#page-back-button')!;
    expect(backBtn.tagName).toBe('BUTTON');
    fireEvent.click(backBtn);

    // Disconnect Sync confirm shows; cancel keeps them on the tracker.
    expect(within(tracker.container).getByText(/Disconnect from this synced session and return to the main menu/i)).toBeInTheDocument();
    fireEvent.click(tracker.container.querySelector('#dialog-cancel-button')!);
    expect(window.location.hash).toBe('#/tracker');

    tracker.unmount();
  });

  it('Keep Players resets to setup and sends the revealed player back to the waiting room', async () => {
    const { storyteller, joinPage } = await renderGameWithRevealedPlayer();
    expect(joinPage.queryAllByText('Washerwoman').length).toBeGreaterThan(0);

    fireEvent.click(storyteller.container.querySelector('#reset-game-button')!);
    await act(async () => {
      fireEvent.click(within(storyteller.container).getByText('Keep Players'));
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    // Storyteller emitted the explicit reset command, kept the session alive
    expect(sentPayloads.some(p => (p.payload as { type?: string }).type === 'game_reset')).toBe(true);
    expect(sentPayloads.some(p => (p.payload as { type?: string }).type === 'storyteller_quit')).toBe(false);

    // Storyteller is back on the setup screen with the player retained
    expect(within(storyteller.container).getByText(/Setup \(1 Players\)/i)).toBeInTheDocument();

    // Alice is back in the waiting room, no longer showing a character
    expect(joinPage.container.querySelector('#waiting-screen')).not.toBeNull();
    expect(joinPage.queryAllByText('Washerwoman').length).toBe(0);

    storyteller.unmount();
    joinPage.unmount();
  });

  it('does NOT boot a revealed player off their character on a bare setup_update (storyteller stepped back to setup)', async () => {
    // Drive the JoinPage directly. A revealed player who receives a plain
    // setup_update — e.g. the storyteller tapped back to setup to tweak
    // something — must stay on their character. Only game_reset moves them.
    const gameCode = 'SHLF';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Alice');
    window.location.hash = '#/join';
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    const deliver = (payload: Record<string, unknown>) => act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage(payload));
    });

    // Reveal Alice via a game_update carrying her role.
    deliver({
      type: 'game_update',
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' }],
      timeOfDay: 'night',
      dayNumber: 1,
      scriptName: 'All Roles',
    });
    expect(joinPage.queryAllByText('Washerwoman').length).toBeGreaterThan(0);

    // A bare setup_update arrives (storyteller back in setup, no reset).
    deliver({
      type: 'setup_update',
      gameType: 'standard',
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' }],
      scriptName: 'All Roles',
      scriptAuthor: '',
      customScriptRoles: null,
    });
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Still on her character, not sent to the waiting room.
    expect(joinPage.container.querySelector('#waiting-screen')).toBeNull();
    expect(joinPage.queryAllByText('Washerwoman').length).toBeGreaterThan(0);

    joinPage.unmount();
  });

  it('reveals a traveler token even under a custom script that omits travelers', async () => {
    // Regression: real uploaded scripts list only townsfolk/outsider/minion/demon
    // — travelers are a universal pool that never appears in customScriptRoles.
    // A player assigned a traveler must still reveal, by falling back to the
    // full official role list rather than staying stuck in the waiting room.
    const gameCode = 'TRVL';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Alice');
    window.location.hash = '#/join';
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    const deliver = (payload: Record<string, unknown>) => act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage(payload));
    });

    // Storyteller adds Alice mid-game as a Gunslinger (traveler) under a custom
    // script whose role list contains no travelers.
    deliver({
      type: 'game_update',
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'gunslinger' }],
      timeOfDay: 'day',
      dayNumber: 1,
      scriptName: 'Custom Script',
      customScriptRoles: [{ id: 'washerwoman', name: 'Washerwoman', team: 'townsfolk' }],
    });

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Revealed as the traveler, not stranded in the waiting room.
    expect(joinPage.container.querySelector('#waiting-screen')).toBeNull();
    expect(joinPage.queryAllByText('Gunslinger').length).toBeGreaterThan(0);

    joinPage.unmount();
  });

  it('sends a player who opened the game tracker (from a join) back to the join waiting room on game_reset', async () => {
    // A joined player who taps "Open Player Game Tracker" navigates to
    // #/tracker (the PlayerTracker component), leaving JoinPage entirely. On a
    // keep-connected reset it must return to the #/join waiting room.
    const gameCode = 'TRKR';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Zoe');
    window.location.hash = '#/tracker';
    const tracker = render(<PlayerTracker theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Storyteller reset (kept players): the explicit reset command arrives.
    act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage({ type: 'game_reset', gameType: 'standard' }));
    });

    expect(window.location.hash).toBe('#/join');

    tracker.unmount();
  });

  it('does NOT navigate a joined game tracker away on a bare setup_update (storyteller stepped back to setup)', async () => {
    const gameCode = 'TRK2';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Zoe');
    window.location.hash = '#/tracker';
    const tracker = render(<PlayerTracker theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage({
          type: 'setup_update',
          gameType: 'standard',
          players: [{ id: 'p1', name: 'Zoe', isDead: false, roleId: '' }],
          scriptName: 'All Roles',
        }));
    });

    // Stays in the tracker — a plain setup_update is not a reset.
    expect(window.location.hash).toBe('#/tracker');

    tracker.unmount();
  });

  it('Whale Bucket: game_reset sends a revealed player to the (empty) preferences picker', async () => {
    const gameCode = 'WBRS';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Zoe');
    window.location.hash = '#/join';
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    const deliver = (payload: Record<string, unknown>) => act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage(payload));
    });

    // Reveal Zoe, then the storyteller does a keep-connected reset.
    deliver({
      type: 'game_update',
      players: [{ id: 'p1', name: 'Zoe', isDead: false, roleId: 'washerwoman' }],
      timeOfDay: 'night',
      dayNumber: 1,
      scriptName: 'All Roles',
    });
    expect(joinPage.queryAllByText('Washerwoman').length).toBeGreaterThan(0);

    deliver({ type: 'game_reset', gameType: 'whale-bucket' });
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 20));
    });

    // Back on the preferences picker, no longer showing a character.
    expect(joinPage.getByText('Submit Your Preferences')).toBeInTheDocument();
    expect(joinPage.queryAllByText('Washerwoman').length).toBe(0);

    joinPage.unmount();
  });

  it('Whale Bucket: a joined game tracker routes to the preferences picker on reset', async () => {
    const gameCode = 'WBTR';
    sessionStorage.setItem('joined-code', gameCode);
    sessionStorage.setItem('joined-name', 'Zoe');
    window.location.hash = '#/tracker';
    const tracker = render(<PlayerTracker theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    act(() => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage({ type: 'game_reset', gameType: 'whale-bucket' }));
    });

    expect(window.location.hash).toBe('#/join?returnTo=preferences');

    tracker.unmount();
  });

  it('JoinPage mounted with ?returnTo=preferences lands directly on the picker', async () => {
    sessionStorage.setItem('joined-code', 'WBLD');
    sessionStorage.setItem('joined-name', 'Zoe');
    window.location.hash = '#/join?returnTo=preferences';
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    expect(joinPage.getByText('Submit Your Preferences')).toBeInTheDocument();
    // The one-shot param is stripped so a refresh won't re-force the picker.
    expect(window.location.hash).toBe('#/join');

    joinPage.unmount();
  });

  it('Disconnect from the reset modal fully ends the session', async () => {
    const { storyteller, joinPage } = await renderGameWithRevealedPlayer();

    fireEvent.click(storyteller.container.querySelector('#reset-game-button')!);
    await act(async () => {
      fireEvent.click(within(storyteller.container).getByText('Disconnect'));
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    expect(sentPayloads.some(p => (p.payload as { type?: string }).type === 'storyteller_quit')).toBe(true);
    expect(window.location.hash).toBe('#/standard');
    expect(joinPage.getByText('The Storyteller has quit the session.')).toBeInTheDocument();

    storyteller.unmount();
    joinPage.unmount();
  });
});

// ---------------------------------------------------------------------------
// Storyteller Device Sync Integration
// ---------------------------------------------------------------------------

const SYNC_CODE = 'SYNC';
const GAME_CODE = 'GAME';

const SYNC_PLAYERS = [
  { id: 'p1', name: 'Alice', isDead: false, roleId: 'imp', isEvil: true },
  { id: 'p2', name: 'Bob', isDead: false, roleId: 'washerwoman' },
  { id: 'p3', name: 'Carol', isDead: false, roleId: 'empath' },
  { id: 'p4', name: 'Dave', isDead: false, roleId: 'poisoner', isEvil: true },
  { id: 'p5', name: 'Eve', isDead: false, roleId: 'butler' },
];

// 10 reminder tokens spread across all 5 players — two per reminder text
const SYNC_REMINDERS: PlacedReminder[] = [
  { id: 'r1',  sourceCharId: 'washerwoman', text: 'Washerwoman', targetPlayerId: 'p1' },
  { id: 'r2',  sourceCharId: 'empath',      text: 'Empath',      targetPlayerId: 'p2' },
  { id: 'r3',  sourceCharId: 'poisoner',    text: 'Poisoned',    targetPlayerId: 'p3' },
  { id: 'r4',  sourceCharId: 'butler',      text: 'Master',      targetPlayerId: 'p4' },
  { id: 'r5',  sourceCharId: 'imp',         text: 'Dead',        targetPlayerId: 'p1' },
  { id: 'r6',  sourceCharId: 'empath',      text: 'Empath',      targetPlayerId: 'p5' },
  { id: 'r7',  sourceCharId: 'poisoner',    text: 'Poisoned',    targetPlayerId: 'p2' },
  { id: 'r8',  sourceCharId: 'washerwoman', text: 'Washerwoman', targetPlayerId: 'p3' },
  { id: 'r9',  sourceCharId: 'imp',         text: 'Dead',        targetPlayerId: 'p4' },
  { id: 'r10', sourceCharId: 'butler',      text: 'Master',      targetPlayerId: 'p5' },
];

function seedPrimary(overrides: Record<string, unknown> = {}) {
  localStorage.setItem('standard-botc-sync-code', SYNC_CODE);
  localStorage.setItem('standard-botc-game-code', GAME_CODE);
  localStorage.setItem('standard-botc-game', JSON.stringify({
    players: SYNC_PLAYERS,
    phase: 'game',
    timeOfDay: 'night',
    dayNumber: 1,
    reminderTokens: SYNC_REMINDERS,
    checkedItems: {},
    customScriptRoles: null,
    scriptName: 'All Roles',
    isLilMonstaGame: false,
    demonBluffs: [],
    gameLog: [],
    ...overrides,
  }));
}

// Delivers a sync_request to all sync-channel subscribers so the primary
// responds immediately, bypassing the 1 s setTimeout in StandardSetup.
async function triggerSync() {
  act(() => {
    activeSubscriptions
      .filter(s => s.gameCode.toLowerCase() === SYNC_CODE.toLowerCase())
      .forEach(s => s.onMessage({ type: 'storyteller_sync_request' }));
  });
  await act(async () => {
    await new Promise(resolve => setTimeout(resolve, 50));
  });
}

// Returns the last storyteller_state_sync payload sent on the sync channel.
function lastSyncState(): Record<string, unknown> | undefined {
  const found = [...sentPayloads]
    .reverse()
    .find(p =>
      p.gameCode.toLowerCase() === SYNC_CODE.toLowerCase() &&
      (p.payload as { type?: string }).type === 'storyteller_state_sync'
    );
  return found ? (found.payload as { state: Record<string, unknown> }).state : undefined;
}

// Renders primary (from localStorage) then secondary (starting fresh), syncs them.
async function renderSyncedPair() {
  window.location.hash = '#/standard';
  const primary = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

  // Secondary must start with no saved game so it truly relies on sync
  localStorage.removeItem('standard-botc-game');

  window.location.hash = `#/standard?syncCode=${SYNC_CODE}&gameCode=${GAME_CODE}`;
  const secondary = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

  await triggerSync();

  return { primary, secondary };
}

describe('Storyteller Device Sync', () => {
  beforeEach(() => {
    localStorage.clear();
    sessionStorage.clear();
    activeSubscriptions.length = 0;
    sentPayloads.length = 0;
    vi.clearAllMocks();
  });

  it('transfers all 10 reminder tokens to the secondary on initial sync', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    const sec = within(secondary.container);

    // All 5 players visible — confirms the game phase was synced
    // (player names may appear more than once, e.g. board + night-order widget)
    for (const name of ['Alice', 'Bob', 'Carol', 'Dave', 'Eve']) {
      expect(sec.getAllByText(name).length).toBeGreaterThan(0);
    }

    // Collect the title attrs of every reminder token button in the secondary board
    const titles = Array.from(
      secondary.container.querySelectorAll<HTMLElement>('button[title]')
    ).map(b => b.getAttribute('title'));

    // Two reminders per text (one on each of two different players)
    expect(titles.filter(t => t === 'Poisoned').length).toBe(2);
    expect(titles.filter(t => t === 'Dead').length).toBe(2);
    expect(titles.filter(t => t === 'Master').length).toBe(2);
    expect(titles.filter(t => t === 'Washerwoman').length).toBe(2);
    expect(titles.filter(t => t === 'Empath').length).toBe(2);

    // Also verify primary shows its own reminders (sanity check)
    const primaryTitles = Array.from(
      primary.container.querySelectorAll<HTMLElement>('button[title]')
    ).map(b => b.getAttribute('title'));
    const knownTexts = new Set(['Poisoned', 'Dead', 'Master', 'Washerwoman', 'Empath']);
    expect(primaryTitles.filter(t => knownTexts.has(t ?? '')).length).toBe(10);

    primary.unmount();
    secondary.unmount();
  });

  it('syncs time-of-day toggle from primary to secondary in real time', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    // Both start at Night 1
    expect(within(primary.container).getAllByText('Night 1').length).toBeGreaterThan(0);
    expect(within(secondary.container).getAllByText('Night 1').length).toBeGreaterThan(0);

    // Click the time-of-day badge on primary to advance to Day 1
    const timeBadge = primary.container.querySelector('#grimoire-info-row');
    expect(timeBadge).not.toBeNull();

    await act(async () => {
      fireEvent.click(timeBadge!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Secondary should now reflect Day 1 without any manual interaction
    expect(within(secondary.container).getAllByText('Day 1').length).toBeGreaterThan(0);

    primary.unmount();
    secondary.unmount();
  });

  it('syncs board rotation offset from primary to secondary', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    const rotateBtn = () => primary.container.querySelector<HTMLElement>(
      'button[title="Rotate counter-clockwise"]'
    );
    expect(rotateBtn()).not.toBeNull();

    // Click rotate three times, one at a time so each state update lands before the next
    for (let i = 0; i < 3; i++) {
      await act(async () => {
        fireEvent.click(rotateBtn()!);
        await new Promise(resolve => setTimeout(resolve, 100));
      });
    }

    // Force a fresh full-state dump from primary and confirm rotationOffset is now 3
    sentPayloads.length = 0;
    await triggerSync();
    const state = lastSyncState();
    expect(state).toBeDefined();
    expect(state!.rotationOffset).toBe(3);

    primary.unmount();
    secondary.unmount();
  });

  it('reminder tokens survive a round-trip: primary → secondary → resync', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    // Confirm all 10 reminders arrived on secondary
    const afterFirstSync = lastSyncState();
    expect((afterFirstSync!.reminderTokens as PlacedReminder[]).length).toBe(10);

    // Trigger a second sync (simulates secondary reconnecting)
    await triggerSync();
    const afterSecondSync = lastSyncState();
    expect((afterSecondSync!.reminderTokens as PlacedReminder[]).length).toBe(10);

    // The same 10 IDs should be present in both syncs
    const ids = (s: Record<string, unknown>) =>
      (s.reminderTokens as PlacedReminder[]).map(r => r.id).sort();
    expect(ids(afterFirstSync!)).toEqual(ids(afterSecondSync!));

    primary.unmount();
    secondary.unmount();
  });

  it('syncs day-number advance alongside time-of-day toggle', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    // Re-query inside each act so the reference is always fresh after re-renders
    const clickTimeBadge = async () => {
      await act(async () => {
        fireEvent.click(primary.container.querySelector('#grimoire-info-row')!);
        await new Promise(resolve => setTimeout(resolve, 150));
      });
    };

    // Night → Day: verify via DOM on secondary
    await clickTimeBadge();
    expect(within(secondary.container).getAllByText('Day 1').length).toBeGreaterThan(0);

    // Day → Night 2: verify via sync payload (more reliable than DOM after multiple toggles)
    sentPayloads.length = 0;
    await clickTimeBadge();
    const nightSync = lastSyncState();
    expect(nightSync).toBeDefined();
    expect(nightSync!.timeOfDay).toBe('night');
    expect(nightSync!.dayNumber).toBe(2);

    primary.unmount();
    secondary.unmount();
  });

  it('syncs the time and day multiple times in a row up to Night 10', async () => {
    seedPrimary();
    const { primary, secondary } = await renderSyncedPair();

    const clickTimeBadge = async () => {
      await act(async () => {
        fireEvent.click(primary.container.querySelector('#grimoire-info-row')!);
        await new Promise(resolve => setTimeout(resolve, 150));
      });
    };

    // Toggle repeatedly: Night 1 -> Day 1 -> Night 2 -> Day 2 -> ... -> Night 10
    // Starting at Night 1, we need 18 toggles to reach Night 10.
    const targetToggles = 18;
    for (let i = 0; i < targetToggles; i++) {
      sentPayloads.length = 0;
      await clickTimeBadge();

      const lastSync = lastSyncState();
      expect(lastSync).toBeDefined();

      const expectedTime = i % 2 === 0 ? 'day' : 'night';
      const expectedDay = Math.floor(i / 2) + 1 + (i % 2 === 0 ? 0 : 1);

      expect(lastSync!.timeOfDay).toBe(expectedTime);
      expect(lastSync!.dayNumber).toBe(expectedDay);
    }

    primary.unmount();
    secondary.unmount();
  });
});

describe('Storyteller Grimoire Bug Fixes', () => {
  beforeEach(() => {
    Element.prototype.scrollIntoView = vi.fn();
    window.history.replaceState({}, '', '#/standard');
    localStorage.clear();
    sessionStorage.clear();
    activeSubscriptions.length = 0;
    sentPayloads.length = 0;
    vi.clearAllMocks();
  });

  it('preserves player alignment on role updates during game phase', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman', isEvil: true },
      { id: 'p2', name: 'Bob', isDead: false, roleId: 'poisoner', isEvil: false }
    ];
    
    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // Open details modal for Alice (Washerwoman, isEvil: true)
    const aliceRow = storyteller.container.querySelector('#ledger-player-p1');
    expect(aliceRow).not.toBeNull();
    
    await act(async () => {
      fireEvent.click(aliceRow!);
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    // Enter character search/selection mode if not already there
    const changeRoleBtn = storyteller.container.querySelector('#detail-change-role-button');
    if (changeRoleBtn) {
      fireEvent.click(changeRoleBtn);
    }

    // Update Alice's role to Empath
    const empathBtn = storyteller.container.querySelector('#detail-role-option-empath');
    expect(empathBtn).not.toBeNull();
    
    await act(async () => {
      fireEvent.click(empathBtn!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Verify Alice's role is updated but alignment (isEvil: true) is preserved
    const saved = JSON.parse(localStorage.getItem('standard-botc-game') || '{}');
    const alice = saved.players.find((p: { id: string; roleId?: string; isEvil?: boolean }) => p.id === 'p1');
    expect(alice).toBeDefined();
    expect(alice!.roleId).toBe('empath');
    expect(alice!.isEvil).toBe(true);

    storyteller.unmount();
  });

  it('storyteller details modal opens conditionally in search mode only if player has no role assigned', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' },
      { id: 'p2', name: 'Bob', isDead: false, roleId: undefined }
    ];
    
    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // 1. Open details modal for Alice (has character 'washerwoman')
    const aliceRow = storyteller.container.querySelector('#ledger-player-p1');
    expect(aliceRow).not.toBeNull();
    
    await act(async () => {
      fireEvent.click(aliceRow!);
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    // Should NOT be in search mode initially (change role button is visible, search input is not present)
    const changeRoleBtnAlice = storyteller.container.querySelector('#detail-change-role-button');
    expect(changeRoleBtnAlice).not.toBeNull();
    const searchInputAlice = storyteller.container.querySelector('#detail-role-search-input');
    expect(searchInputAlice).toBeNull();

    // Close details modal
    const closeBtn = storyteller.container.querySelector('[aria-label="Close modal"]');
    if (closeBtn) {
      await act(async () => {
        fireEvent.click(closeBtn);
        await new Promise(resolve => setTimeout(resolve, 50));
      });
    }

    // 2. Open details modal for Bob (has no character assigned)
    const bobRow = storyteller.container.querySelector('#ledger-player-p2');
    expect(bobRow).not.toBeNull();
    
    await act(async () => {
      fireEvent.click(bobRow!);
    });

    await waitFor(() => {
      const searchInputBob = storyteller.container.querySelector('#detail-role-search-input');
      expect(searchInputBob).not.toBeNull();
    });

    const changeRoleBtnBob = storyteller.container.querySelector('#detail-change-role-button');
    expect(changeRoleBtnBob).toBeNull();

    storyteller.unmount();
  });

  it('warns before declaring a winner when a player is synced in (regression check)', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' },
    ];

    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = localStorage.getItem('standard-botc-game-code');

    // Alice joins remotely, matching the existing seeded player by name
    sessionStorage.setItem('joined-code', gameCode!);
    sessionStorage.setItem('joined-name', 'Alice');
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    fireEvent.click(within(storyteller.container).getByText('🌟 Good Wins'));

    expect(within(storyteller.container).getByText(/Declare Good the winner\?/i)).toBeInTheDocument();

    storyteller.unmount();
    joinPage.unmount();
  });

  it('warns before declaring a winner in Whale Bucket mode too (parity with Standard)', async () => {
    const preferences = { townsfolk: [], outsider: [], minion: [], demon: [], traveler: [] };
    localStorage.setItem('whale-bucket-game', JSON.stringify({
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman', preferences }],
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    }));

    window.location.hash = '#/whale-bucket';
    const storyteller = render(<WhaleBucket theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = localStorage.getItem('whale-bucket-game-code');

    sessionStorage.setItem('joined-code', gameCode!);
    sessionStorage.setItem('joined-name', 'Alice');
    const joinPage = render(<JoinPage theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    fireEvent.click(within(storyteller.container).getByText('🌟 Good Wins'));

    expect(within(storyteller.container).getByText(/Declare Good the winner\?/i)).toBeInTheDocument();

    storyteller.unmount();
    joinPage.unmount();
  });

  it('Whale Bucket: warns before opening the grimoire when players are connected (parity with Standard)', async () => {
    const preferences = { townsfolk: [], outsider: [], minion: [], demon: [], traveler: [] };
    localStorage.setItem('whale-bucket-game-code', 'WBOG');
    localStorage.setItem('whale-bucket-sync-code', 'WBOS');
    localStorage.setItem('whale-bucket-game', JSON.stringify({
      players: [
        { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman', preferences },
        { id: 'p2', name: 'Bob', isDead: false, roleId: 'chef', preferences },
        { id: 'p3', name: 'Cara', isDead: false, roleId: 'empath', preferences },
        { id: 'p4', name: 'Dave', isDead: false, roleId: 'poisoner', preferences },
        { id: 'p5', name: 'Eve', isDead: false, roleId: 'imp', preferences },
      ],
      phase: 'draft',
    }));
    window.location.hash = '#/whale-bucket';
    const storyteller = render(<WhaleBucket theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = 'WBOG';

    await act(async () => { await new Promise(r => setTimeout(r, 50)); });

    // A connected player announces herself so remotePlayerCount > 0.
    await act(async () => {
      activeSubscriptions
        .filter(s => s.gameCode.toLowerCase() === gameCode.toLowerCase())
        .forEach(s => s.onMessage({ type: 'player_join', id: 'p1', name: 'Alice' }));
      await new Promise(r => setTimeout(r, 50));
    });

    const openBtn = storyteller.container.querySelector('#open-grimoire-button') as HTMLButtonElement;
    expect(openBtn).not.toBeNull();
    expect(openBtn.disabled).toBe(false);

    // Open Grimoire → confirmation modal appears instead of silently starting.
    fireEvent.click(openBtn);
    expect(within(storyteller.container).getByText('Send character assignments?')).toBeInTheDocument();

    // Confirm → the game starts (leaves the draft phase).
    await act(async () => {
      fireEvent.click(storyteller.container.querySelector('#confirm-open-grimoire-button-whale')!);
      await new Promise(r => setTimeout(r, 50));
    });
    expect(storyteller.container.querySelector('#open-grimoire-button')).toBeNull();

    storyteller.unmount();
  });

  it('Whale Bucket: manual-assign-characters-button transitions to draft and retains assigned characters', async () => {
    // 1. Render with 0 players to verify disabled state
    localStorage.setItem('whale-bucket-game', JSON.stringify({
      players: [],
      phase: 'setup',
    }));
    window.location.hash = '#/whale-bucket';
    let storyteller = render(<WhaleBucket theme="dark" toggleTheme={vi.fn()} />);
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });
    let manualBtn = storyteller.container.querySelector('#manual-assign-characters-button');
    expect(manualBtn).not.toBeNull();
    expect(manualBtn).toBeDisabled();
    storyteller.unmount();

    // 2. Render with players, one having an assigned character
    localStorage.setItem('whale-bucket-game', JSON.stringify({
      players: [
        { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' },
        { id: 'p2', name: 'Bob', isDead: false },
      ],
      phase: 'setup',
    }));
    storyteller = render(<WhaleBucket theme="dark" toggleTheme={vi.fn()} />);
    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    manualBtn = storyteller.container.querySelector('#manual-assign-characters-button');
    expect(manualBtn).not.toBeNull();
    expect(manualBtn).not.toBeDisabled();

    // Click "Manually Assign"
    fireEvent.click(manualBtn!);

    // Should transition to draft (Character Assignment) phase
    expect(storyteller.getByText(/2. Character Assignment/i)).toBeInTheDocument();

    // Bob still has no character, so "Open Grimoire" is disabled
    const openGrimBtn = storyteller.container.querySelector('#open-grimoire-button');
    expect(openGrimBtn).toBeDisabled();

    storyteller.unmount();
  });

  it('persists both name and notes when edited together and the modal is closed (regression: stale-closure race)', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' },
    ];

    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    const aliceRow = storyteller.container.querySelector('#ledger-player-p1');
    expect(aliceRow).not.toBeNull();

    await act(async () => {
      fireEvent.click(aliceRow!);
      await new Promise(resolve => setTimeout(resolve, 100));
    });

    const nameInput = storyteller.container.querySelector('#detail-player-name-input') as HTMLInputElement;
    const notesInput = storyteller.container.querySelector('input[placeholder="Notes..."]') as HTMLInputElement;
    expect(nameInput).not.toBeNull();
    expect(notesInput).not.toBeNull();

    fireEvent.change(nameInput, { target: { value: 'Alicia' } });
    fireEvent.change(notesInput, { target: { value: 'Watch this one' } });

    const closeBtn = storyteller.container.querySelector('#detail-close-button');
    expect(closeBtn).not.toBeNull();

    await act(async () => {
      fireEvent.click(closeBtn!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    const saved = JSON.parse(localStorage.getItem('standard-botc-game') || '{}');
    const alice = saved.players.find((p: { id: string; name?: string; notes?: string }) => p.id === 'p1');
    expect(alice).toBeDefined();
    expect(alice!.name).toBe('Alicia');
    expect(alice!.notes).toBe('Watch this one');

    storyteller.unmount();
  });

  it('clears checklist checkboxes on day/night transitions', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman' }
    ];
    
    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
      checkedItems: { 'washerwoman-p1': true }
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // Click the time-of-day badge to toggle from Night 1 to Day 1
    const timeBadge = storyteller.container.querySelector('#grimoire-info-row');
    expect(timeBadge).not.toBeNull();

    await act(async () => {
      fireEvent.click(timeBadge!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Verify checkedItems is empty in local storage
    const saved = JSON.parse(localStorage.getItem('standard-botc-game') || '{}');
    expect(saved.checkedItems).toEqual({});

    storyteller.unmount();
  });

  it('renders correct character tokens (Drunk/Marionette/Lunatic) with fake role name on board', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'imp', isTheLunatic: true },
      { id: 'p2', name: 'Bob', isDead: false, roleId: 'empath', isTheMarionette: true },
      { id: 'p3', name: 'Carol', isDead: false, roleId: 'washerwoman', isTheDrunk: true },
    ];
    
    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // Verify that the text on the board shows the underlying character token
    expect(within(storyteller.container).getByText('LUNATIC')).toBeInTheDocument();
    expect(within(storyteller.container).getByText('MARIONETTE')).toBeInTheDocument();
    expect(within(storyteller.container).getByText('DRUNK')).toBeInTheDocument();

    storyteller.unmount();
  });

  it('preserves bag setup state (selectedCharacterIds) in standard setup when switching phases', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', roleId: 'imp' },
      { id: 'p2', name: 'Bob', roleId: 'washerwoman' },
      { id: 'p3', name: 'Carol', roleId: 'empath' },
      { id: 'p4', name: 'Dave', roleId: 'poisoner' },
      { id: 'p5', name: 'Eve', roleId: 'monk' }
    ];
    
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: PLAYERS,
      phase: 'setup',
      timeOfDay: 'night',
      dayNumber: 1,
      selectedCharacterIds: ['imp', 'poisoner'],
    }));

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    const startButton = storyteller.container.querySelector('#open-grimoire-button');

    expect(startButton).not.toBeNull();
    
    await act(async () => {
      fireEvent.click(startButton!);
      await new Promise(resolve => setTimeout(resolve, 150));
    });

    // Verify phase is now game and selectedCharacterIds is still ['imp', 'poisoner']
    const saved = JSON.parse(localStorage.getItem('standard-botc-game') || '{}');
    expect(saved.phase).toBe('game');
    expect(saved.selectedCharacterIds).toEqual(['imp', 'poisoner']);

    storyteller.unmount();
  });

  it('renders selected demon for Lunatic in details modal, grimoire board, and game phase list', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', isDead: false, roleId: 'imp', isTheLunatic: true },
    ];
    
    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // 1. Verify Grimoire Board displays the selected Demon (Imp) name on the token and badge
    expect(within(storyteller.container).getByText('LUNATIC')).toBeInTheDocument();
    
    // The main token text should show "Imp"
    const boardTokens = storyteller.container.querySelectorAll('textPath');
    const tokenNames = Array.from(boardTokens).map(el => el.textContent);
    expect(tokenNames).toContain('Imp');
    expect(tokenNames).not.toContain('Lunatic');

    // 2. Open details modal for Alice
    const playerToken = storyteller.container.querySelector('#grimoire-player-p1');
    expect(playerToken).not.toBeNull();
    await act(async () => {
      fireEvent.click(playerToken!);
      await new Promise(resolve => setTimeout(resolve, 150));
    });

    // Verify Details Modal shows "Imp" instead of "Lunatic" as the character title
    const modalTextPaths = storyteller.container.querySelectorAll('textPath');
    const modalTokenNames = Array.from(modalTextPaths).map(el => el.textContent);
    expect(modalTokenNames).toContain('Imp');

    // Close details modal
    const closeBtn = storyteller.container.querySelector('#detail-close-button');
    expect(closeBtn).not.toBeNull();
    await act(async () => {
      fireEvent.click(closeBtn!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // 3. Switch to Game Phase view / check player list
    const sidebarRoleNames = Array.from(storyteller.container.querySelectorAll('.truncate')).map(el => el.textContent);
    // Should show the Demon role name (Imp) next to the player name
    expect(sidebarRoleNames).toContain('Imp');
    expect(sidebarRoleNames).not.toContain('Lunatic');

    storyteller.unmount();
  });

  it('renders assigned good role for Marionette in details modal, grimoire board, and game phase list', async () => {
    // Marionette is always assigned a good role (Townsfolk/Outsider) — they think they are that character
    const PLAYERS = [
      { id: 'p1', name: 'Bob', isDead: false, roleId: 'washerwoman', isTheMarionette: true },
    ];

    seedPrimary({
      players: PLAYERS,
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    });

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // 1. Verify Grimoire Board displays the assigned Townsfolk (Washerwoman) name on the token and badge
    expect(within(storyteller.container).getByText('MARIONETTE')).toBeInTheDocument();

    const boardTokens = storyteller.container.querySelectorAll('textPath');
    const tokenNames = Array.from(boardTokens).map(el => el.textContent);
    expect(tokenNames).toContain('Washerwoman');
    expect(tokenNames).not.toContain('Marionette');

    // 2. Open details modal for Bob
    const playerToken = storyteller.container.querySelector('#grimoire-player-p1');
    expect(playerToken).not.toBeNull();
    await act(async () => {
      fireEvent.click(playerToken!);
      await new Promise(resolve => setTimeout(resolve, 150));
    });

    // Verify Details Modal shows "Washerwoman" instead of "Marionette" as the character title
    const modalTextPaths = storyteller.container.querySelectorAll('textPath');
    const modalTokenNames = Array.from(modalTextPaths).map(el => el.textContent);
    expect(modalTokenNames).toContain('Washerwoman');

    // Close details modal
    const closeBtn = storyteller.container.querySelector('#detail-close-button');
    expect(closeBtn).not.toBeNull();
    await act(async () => {
      fireEvent.click(closeBtn!);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // 3. Check player list in sidebar
    const sidebarRoleNames = Array.from(storyteller.container.querySelectorAll('.truncate')).map(el => el.textContent);
    expect(sidebarRoleNames).toContain('Washerwoman');
    expect(sidebarRoleNames).not.toContain('Marionette');

    storyteller.unmount();
  });

  it('disables Open Grimoire when there are failures, and enables it when override failures checkbox is checked', async () => {
    const PLAYERS = [
      { id: 'p1', name: 'Alice', roleId: 'imp' },
      { id: 'p2', name: 'Bob', roleId: 'washerwoman' },
      { id: 'p3', name: 'Carol', roleId: 'empath' },
      { id: 'p4', name: 'Dave', roleId: 'poisoner' },
      { id: 'p5', name: 'Eve', roleId: 'imp' } // Duplicate Imp!
    ];
    
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: PLAYERS,
      phase: 'setup',
      timeOfDay: 'night',
      dayNumber: 1,
    }));

    window.location.hash = '#/standard';
    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);

    // Retrieve the Open Grimoire button
    const openGrimBtn = storyteller.container.querySelector('#open-grimoire-button');
    expect(openGrimBtn).not.toBeNull();
    // It should be disabled because there is a duplicate Imp (which is a failure)
    expect(openGrimBtn).toBeDisabled();

    // Verify the override checkbox is present
    const overrideCheckbox = storyteller.container.querySelector('#override-failures-checkbox') as HTMLInputElement;
    expect(overrideCheckbox).not.toBeNull();
    expect(overrideCheckbox.checked).toBe(false);

    // Check the checkbox
    await act(async () => {
      fireEvent.click(overrideCheckbox);
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // The button should now be enabled
    expect(openGrimBtn).not.toBeDisabled();

    storyteller.unmount();
  });
});

describe('Storyteller Notes Privacy', () => {
  beforeEach(() => {
    localStorage.clear();
    sessionStorage.clear();
    activeSubscriptions.length = 0;
    sentPayloads.length = 0;
    vi.clearAllMocks();
  });

  it('never broadcasts the storyteller\'s private player notes to a synced client', async () => {
    window.location.hash = '#/standard';
    localStorage.setItem('standard-botc-game', JSON.stringify({
      players: [{ id: 'p1', name: 'Alice', isDead: false, roleId: 'washerwoman', notes: 'Secretly suspicious of everyone' }],
      phase: 'game',
      timeOfDay: 'night',
      dayNumber: 1,
    }));

    const storyteller = render(<StandardSetup theme="dark" toggleTheme={vi.fn()} />);
    const gameCode = localStorage.getItem('standard-botc-game-code');

    sessionStorage.setItem('joined-code', gameCode!);
    const tracker = render(<PlayerTracker theme="dark" toggleTheme={vi.fn()} />);

    await act(async () => {
      await new Promise(resolve => setTimeout(resolve, 50));
    });

    // Every payload sent to players (game_update / setup_update) must never carry `notes`
    const leaked = sentPayloads.some(p => {
      const payload = p.payload as { players?: Array<{ notes?: string }> };
      return payload.players?.some(pl => pl.notes !== undefined);
    });
    expect(leaked).toBe(false);
    expect(sentPayloads.length).toBeGreaterThan(0);

    // And the note text itself should never reach the player's rendered UI
    expect(within(tracker.container).queryByText(/Secretly suspicious/)).toBeNull();

    storyteller.unmount();
    tracker.unmount();
  });
});
